name: autotest

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
    - name: install tools
      run: |
        sudo apt update
        sudo apt install ruby g++ npm clang
    - name: autotest
      run: |
        ruby tools/autotest.rb -j 2
