name: autotest

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: "3.2"
    - name: install tools
      run: |
        sudo apt update
        sudo apt install g++ clang
    - name: autotest
      run: |
        ruby tools/autotest.rb -j 2
