name: buildtest

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: "3.2"
    - name: install tools
      run: |
        sudo apt install g++ clang
    - name: test
      run: |
        ruby tools/buildtest.rb -j 2
