name: update-htmldoc

# yarn upgrade
# Upgrade yarn.lock
# cf. yarn upgrade --latest
# 
# bundle update
# Upgrade Gemfile.lock

on: [push]
# on:
#   schedule:
#     - cron: 0 12 * * 5  # At 12:00 on Friday.

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: doc-codeLib2
        # ref: master
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Please tell me who you are.
      run: |
        git config --global user.email "mai@ukibune.net"
        git config --global user.name "mai bot-worker"
    - name: merge from master
      run: |
        git merge master
    - name: get codeLib2-htmldoc
      run: |
        git clone https://github.com/buyoh/codeLib2-htmldoc.git /tmp/tools/htmldoc
        cd /tmp/tools/htmldoc && yarn 
    - name: generate by codeLib2-htmldoc
      run: |
        CODELIB_PATH=`pwd`
        pushd /tmp/tools/htmldoc
        ruby tools/codelib_json_bundler.rb --codelib-path ${CODELIB_PATH} --minimize
        yarn build
        ruby tools/generate_release_directory.rb --output-path ${CODELIB_PATH}/docs
        popd
    - name: commit phase
      run: |
        if [ `git diff | wc -l` -ne 0 ] ; then
        git add docs/*
        git commit -m 'update htmldoc by Github Actions'
        fi
    - name: push
      run: |
        git push
