name: update-htmldoc

# yarn upgrade
# Upgrade yarn.lock
# cf. yarn upgrade --latest
#
# bundle update
# Upgrade Gemfile.lock

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          submodules: recursive
      - uses: actions/setup-node@v1
        with:
          node-version: "20"
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - uses: dtolnay/rust-toolchain@stable
      - name: Please tell me who you are.
        run: |
          git config --global user.email "53999520+mai-w@users.noreply.github.com"
          git config --global user.name "mai bot-worker"
      - name: unshallow
        run: |
          git fetch --unshallow ||:
      - name: prepare codeLib2-htmldoc
        run: |
          cd tools/codeLib2-htmldoc && yarn
      - name: prepare codeLib2-tools
        run: |
          (cd tools/codeLib2-tools && cargo build --release --bins)
          cp -ar .github/workflows /tmp/
      - name: generate by codeLib2-htmldoc
        run: |
          bash ./.github/workflows/htmldoc_gen.sh
      - uses: actions/checkout@v2
        with:
          ref: doc
      - name: commit phase
        run: |
          # scripts in the doc branch may be obsoleted
          bash /tmp/workflows/htmldoc_commit.sh
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: doc