name: pullrequest-checker

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: install tools
      run: |
        sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main'
        sudo apt update
        sudo apt install clang-format
        sudo apt install ruby gem g++ npm
        sudo npm i -g eslint 
    - name: refactor
      run: |
        ruby tools/refactor.rb --inplace
        if [ `git diff | wc -l` -ne 0 ] ; then
        git add .
        git commit -m 'build by Github Actions'
        fi
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
