name: pullrequest-checker

on:
  push:
    branches:
    - master
  pull_request:
    tags:
    - review

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
    - name: install tools
      run: |
        sudo apt update
        sudo apt install clang-format
        sudo apt install ruby gem g++ npm
        sudo npm i -g eslint
        git config --global user.email "53999520+mai-w@users.noreply.github.com"
        git config --global user.name "mai-w"
    - name: refactor
      run: |
        bash tools/javascript-linter/lint.sh
        ruby tools/refactor.rb --inplace
        git add .
        git commit -m 'refactor by Github Actions' ||:
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
