name: pullrequest-checker

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    tags:
    - review

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: "20"
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: "3.2"
    - name: install tools
      run: |
        sudo apt update
        sudo apt install clang-format g++
        git config --global user.email "53999520+mai-w@users.noreply.github.com"
        git config --global user.name "mai-w"
    - name: refactor
      run: |
        bash tools/javascript-linter/lint.sh
        ruby tools/refactor.rb --inplace
        git add .
        git commit -m 'refactor by Github Actions' ||:
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
